INFO 2025-06-29 21:03:45,925 autoreload 3984 7256 Watching for file changes with StatReloader
ERROR 2025-06-29 21:03:58,625 log 3984 11288 Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\generic\base.py", line 98, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\IDAN\alx-backend-graphql_crm\alx-backend-graphql\schema.py", line 2, in <module>
    from crm.schema import Query as CRMQuery, Mutation as CRMMutation
  File "C:\Users\IDAN\alx-backend-graphql_crm\crm\schema.py", line 31, in <module>
    class ProductFilter(FilterSet):
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
TypeError: 'Meta.fields' must not contain non-model field names: sku, stock_quantity
ERROR 2025-06-29 21:03:58,672 basehttp 3984 11288 "GET /graphql HTTP/1.1" 500 149785
WARNING 2025-06-29 21:04:00,052 log 3984 11288 Not Found: /favicon.ico
WARNING 2025-06-29 21:04:00,055 basehttp 3984 11288 "GET /favicon.ico HTTP/1.1" 404 2702
ERROR 2025-06-29 21:05:21,156 log 3984 11288 Internal Server Error: /graphql
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django\views\generic\base.py", line 98, in view
    self = cls(**initkwargs)
           ^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\views.py", line 114, in __init__
    schema = graphene_settings.SCHEMA
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 127, in __getattr__
    val = perform_import(val, attr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 66, in perform_import
    return import_from_string(val, setting_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\graphene_django\settings.py", line 80, in import_from_string
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\IDAN\alx-backend-graphql_crm\alx-backend-graphql\schema.py", line 2, in <module>
    from crm.schema import Query as CRMQuery, Mutation as CRMMutation
  File "C:\Users\IDAN\alx-backend-graphql_crm\crm\schema.py", line 31, in <module>
    class ProductFilter(FilterSet):
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 82, in __new__
    new_class.base_filters = new_class.get_filters()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\django_filters\filterset.py", line 371, in get_filters
    raise TypeError(
TypeError: 'Meta.fields' must not contain non-model field names: sku, stock_quantity
ERROR 2025-06-29 21:05:21,188 basehttp 3984 11288 "GET /graphql HTTP/1.1" 500 149791
INFO 2025-06-29 21:07:36,445 basehttp 3984 11276 "GET /graphql HTTP/1.1" 200 2611
INFO 2025-06-29 21:07:36,870 basehttp 3984 11276 "GET /static/graphene_django/graphiql.js HTTP/1.1" 200 4037
INFO 2025-06-29 21:07:38,012 basehttp 3984 11276 "POST /graphql HTTP/1.1" 200 61060
INFO 2025-06-29 21:16:20,295 autoreload 3984 7256 C:\Users\IDAN\alx-backend-graphql_crm\crm\schema.py changed, reloading.
INFO 2025-06-29 21:16:23,135 autoreload 7552 16108 Watching for file changes with StatReloader
INFO 2025-06-29 21:18:15,544 autoreload 12068 16216 Watching for file changes with StatReloader
INFO 2025-06-29 21:18:23,564 basehttp 7552 16540 "POST /graphql HTTP/1.1" 200 1072
INFO 2025-06-29 21:18:36,458 basehttp 7552 16540 "POST /graphql HTTP/1.1" 200 1072
INFO 2025-06-29 21:20:20,907 basehttp 7552 272 "POST /graphql HTTP/1.1" 200 247
INFO 2025-06-29 21:20:20,970 basehttp 7552 15004 "POST /graphql HTTP/1.1" 200 217
INFO 2025-06-29 21:20:21,024 basehttp 7552 1508 "POST /graphql HTTP/1.1" 200 33
INFO 2025-06-29 21:20:21,068 basehttp 7552 15624 "POST /graphql HTTP/1.1" 200 33
INFO 2025-06-29 21:20:21,094 basehttp 7552 4032 "POST /graphql HTTP/1.1" 200 421
INFO 2025-06-29 21:20:21,131 basehttp 7552 4756 "POST /graphql HTTP/1.1" 200 801
INFO 2025-06-29 21:20:21,244 basehttp 7552 14876 "POST /graphql HTTP/1.1" 200 162
INFO 2025-06-29 21:20:21,356 basehttp 7552 17268 "POST /graphql HTTP/1.1" 200 534
INFO 2025-06-29 21:20:21,458 basehttp 7552 13404 "POST /graphql HTTP/1.1" 200 32
INFO 2025-06-29 21:20:21,541 basehttp 7552 8480 "POST /graphql HTTP/1.1" 200 154
WARNING 2025-06-29 21:20:21,656 log 7552 15812 Bad Request: /graphql
WARNING 2025-06-29 21:20:21,706 basehttp 7552 15812 "POST /graphql HTTP/1.1" 400 246
INFO 2025-06-29 21:20:21,760 basehttp 7552 14416 "POST /graphql HTTP/1.1" 200 30
WARNING 2025-06-29 21:20:21,844 log 7552 7052 Bad Request: /graphql
WARNING 2025-06-29 21:20:22,034 basehttp 7552 7052 "POST /graphql HTTP/1.1" 400 128
INFO 2025-06-29 21:20:22,405 basehttp 7552 11940 "POST /graphql HTTP/1.1" 200 382
INFO 2025-06-29 21:20:22,732 basehttp 7552 6576 "POST /graphql HTTP/1.1" 200 979
INFO 2025-06-29 21:20:22,913 basehttp 7552 7132 "POST /graphql HTTP/1.1" 200 712
WARNING 2025-06-29 21:22:23,654 log 7552 15528 Bad Request: /graphql
WARNING 2025-06-29 21:22:23,670 basehttp 7552 15528 "POST /graphql HTTP/1.1" 400 142
WARNING 2025-06-29 21:22:23,712 log 7552 12272 Bad Request: /graphql
WARNING 2025-06-29 21:22:23,724 basehttp 7552 12272 "POST /graphql HTTP/1.1" 400 249
WARNING 2025-06-29 21:22:23,780 log 7552 5712 Bad Request: /graphql
WARNING 2025-06-29 21:22:23,789 basehttp 7552 5712 "POST /graphql HTTP/1.1" 400 266
INFO 2025-06-29 21:22:23,857 basehttp 7552 14280 "POST /graphql HTTP/1.1" 200 33
INFO 2025-06-29 21:22:24,097 basehttp 7552 5624 "POST /graphql HTTP/1.1" 200 162
WARNING 2025-06-29 21:22:24,228 log 7552 1560 Bad Request: /graphql
WARNING 2025-06-29 21:22:24,277 basehttp 7552 1560 "POST /graphql HTTP/1.1" 400 127
INFO 2025-06-29 21:22:24,338 basehttp 7552 11924 "POST /graphql HTTP/1.1" 200 327
INFO 2025-06-29 21:22:24,408 basehttp 7552 13652 "POST /graphql HTTP/1.1" 200 32
WARNING 2025-06-29 21:22:24,549 log 7552 9184 Bad Request: /graphql
WARNING 2025-06-29 21:22:24,567 basehttp 7552 9184 "POST /graphql HTTP/1.1" 400 127
INFO 2025-06-29 21:22:24,641 basehttp 7552 10456 "POST /graphql HTTP/1.1" 200 382
INFO 2025-06-29 21:22:24,695 basehttp 7552 11328 "POST /graphql HTTP/1.1" 200 533
INFO 2025-06-29 21:22:24,762 basehttp 7552 16568 "POST /graphql HTTP/1.1" 200 534
INFO 2025-06-29 21:22:25,025 basehttp 7552 16972 "POST /graphql HTTP/1.1" 200 274
INFO 2025-06-29 21:41:36,016 autoreload 7552 16108 C:\Users\IDAN\alx-backend-graphql_crm\crm\filters.py changed, reloading.
INFO 2025-06-29 21:41:47,104 autoreload 14640 10308 Watching for file changes with StatReloader
INFO 2025-06-29 21:42:16,790 basehttp 12068 10800 "POST /graphql HTTP/1.1" 200 36
INFO 2025-06-29 21:42:21,901 autoreload 16864 1364 Watching for file changes with StatReloader
INFO 2025-06-29 21:42:29,947 basehttp 12068 11356 "POST /graphql HTTP/1.1" 200 36
WARNING 2025-06-29 21:44:53,154 log 12068 9412 Bad Request: /graphql
WARNING 2025-06-29 21:44:53,165 basehttp 12068 9412 "POST /graphql HTTP/1.1" 400 142
WARNING 2025-06-29 21:44:53,197 log 12068 14088 Bad Request: /graphql
WARNING 2025-06-29 21:44:53,197 basehttp 12068 14088 "POST /graphql HTTP/1.1" 400 249
WARNING 2025-06-29 21:44:53,264 log 12068 9080 Bad Request: /graphql
WARNING 2025-06-29 21:44:53,267 basehttp 12068 9080 "POST /graphql HTTP/1.1" 400 266
INFO 2025-06-29 21:44:53,352 basehttp 12068 8056 "POST /graphql HTTP/1.1" 200 33
INFO 2025-06-29 21:44:53,416 basehttp 12068 14576 "POST /graphql HTTP/1.1" 200 162
WARNING 2025-06-29 21:44:53,453 log 12068 17296 Bad Request: /graphql
WARNING 2025-06-29 21:44:53,466 basehttp 12068 17296 "POST /graphql HTTP/1.1" 400 127
INFO 2025-06-29 21:44:53,535 basehttp 12068 15980 "POST /graphql HTTP/1.1" 200 327
INFO 2025-06-29 21:44:53,592 basehttp 12068 14704 "POST /graphql HTTP/1.1" 200 32
WARNING 2025-06-29 21:44:53,649 log 12068 4532 Bad Request: /graphql
WARNING 2025-06-29 21:44:53,651 basehttp 12068 4532 "POST /graphql HTTP/1.1" 400 127
INFO 2025-06-29 21:44:53,734 basehttp 12068 16424 "POST /graphql HTTP/1.1" 200 382
INFO 2025-06-29 21:44:53,785 basehttp 12068 7768 "POST /graphql HTTP/1.1" 200 533
INFO 2025-06-29 21:44:53,836 basehttp 12068 11584 "POST /graphql HTTP/1.1" 200 534
INFO 2025-06-29 21:44:53,930 basehttp 12068 1292 "POST /graphql HTTP/1.1" 200 274
